run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - dupl
    - wsl
    - goerr113 
    - nestif
    - exhaustivestruct
    - paralleltest
    - gci
    - wrapcheck
    - godox
    - interfacer
    - maligned
    - golint
    - scopelint
    - tagliatelle
    - funlen
    - cyclop
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 40
  gocognit:
    # minimal code complexity to report, 30 by default
    min-complexity: 120
  funlen:
    lines: 80
