# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod download
    - go mod tidy
builds:
- binary: '{{ .ProjectName }}_v{{ .Version }}'
  env:
    # goreleaser does not work with CGO, it could also complicate
    # usage by users in CI/CD systems like Terraform Cloud where
    # they are unable to install libraries.
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - "-s"
    - "-w"
    - "-X main.version={{.Version}}"
    - "-X main.commit={{.Commit}}"
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: '386'
archives:
- format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
    - LICENSE*
    - README*
    - config.yaml.sample
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request'
