name: golangci-lint

on:
  push:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - ".golangci.yml"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - ".golangci.yml"
      - ".github/workflows/lint.yml"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
